"use client";
import {useEffect,useState} from "react";
import {ArrowUpRight,ChevronLeft,ChevronRight,Clock3,Instagram,MapPin,Menu,Phone,Star,X} from "lucide-react";
import OwnerPanel from "../components/OwnerPanel";

const seed=[
{src:"https://lh3.googleusercontent.com/gps-cs-s/ANWiy9T1gZa4o8Bou6frO_lOO84DfGWtkeyYDFMDAHoVtvTGEShUrrXn8mMjTkSsOfdDAPENZMoX2XfQZTpBTfvQyL4wT-gLU_fRzilA4PZbfN9QIftqnEvGQnIGgTh82AyrqrBhOswqFEJzFt9D=w645-h298-k-no",alt:"Weta Cafe"},
{src:"https://lh3.googleusercontent.com/gps-cs-s/ANWiy9SX7yCx7da8OalHoQ_xsVwFjsUtLb4akkxyrhZiwEO_uwqE_XJt_acgSyGenjGT_Qfxpb9VXYH4zfyxjbs2jGk3uU4Hk6VmMNTp7ZCCse_MIRU-Y_tCduP7Ub0S2LpXCRWh1M1FrE34UP_6=w224-h298-k-no",alt:"Wnętrze Weta Cafe"},
{src:"https://lh3.googleusercontent.com/gps-cs-s/ANWiy9SySj7g3_vpoJE2UUdIGD5USAH12BUHwuPh3_fHLAQqQvesS8H3TSpTGAHS5kOEZWX3RSjQOjNwyvBghe4N6cKZbc3R2hjE9Vifflk0c-s77XTuAqJzKVBJ_xv_3DY4Xqo5Gnlvwh18Rc_s=w224-h298-k-no",alt:"Jedzenie i napoje"},
{src:"https://lh3.googleusercontent.com/gps-cs-s/ANWiy9TQS1Qn3qQpVVQd6a8PHFZsZqwhx-vCK5MvyAzESgu_F5sC1xiF-jm4gQV4esgGHRMmtnMwzGaRhedLer8ddnk1ptZYEVcZ32eJvUObgNPv16uUQlSHUYAQkuurSS8LPnL0stILd0QPOuZi=w224-h298-k-no",alt:"Klimat Weta Cafe"},
{src:"https://lh3.googleusercontent.com/gps-cs-s/ANWiy9TBvBU9LFWaXcja4e1MdrmynSsGEOI_jEPH609Lhmn2Gl1ZKoQKClweZZjT1XPfiDm7UwgUkAQ3Ayv7y9gaehAhpR6lKTzZh5LPnEID3u2BP7wegzcW06wsx3FDd1so0XDudN214Y77p7DL=w224-h298-k-no",alt:"Kawa w Weta Cafe"}
];

export default function Home(){
 const [photos,setPhotos]=useState(seed),[open,setOpen]=useState<number|null>(null),[panel,setPanel]=useState(false),[menu,setMenu]=useState(false);
 useEffect(()=>{const s=localStorage.getItem("weta-gallery");if(s)try{setPhotos(JSON.parse(s))}catch{}},[]);
 const next=()=>open!==null&&setOpen((open+1)%photos.length),prev=()=>open!==null&&setOpen((open-1+photos.length)%photos.length);
 return <main>
 <header className="nav"><a className="brand" href="#">WETA<span>CAFE</span></a><nav className={menu?"show":""}><a href="#o-nas">O nas</a><a href="#menu">Menu</a><a href="#galeria">Galeria</a><a href="#opinie">Opinie</a><a href="#kontakt">Kontakt</a></nav><a className="nav-cta" href="https://www.google.com/maps/dir/?api=1&destination=Jana+Mikulicza-Radeckiego+6,+Wroc%C5%82aw" target="_blank">Wyznacz trasę <ArrowUpRight size={16}/></a><button className="hamb" onClick={()=>setMenu(!menu)}><Menu/></button></header>
 <section className="hero"><div className="hero-copy"><p className="eyebrow">WROCŁAW · NADODRZE / OŁBIN</p><h1>Dobra kawa.<br/><em>Małe przyjemności.</em></h1><p className="lead">Weta Cafe to kameralna kawiarnia przy Mikulicza-Radeckiego. Espresso, ceremonialna matcha i coś słodkiego, bez zadęcia.</p><div className="hero-actions"><a className="button" href="#menu">Zobacz menu <ArrowUpRight size={17}/></a><a className="text-link" href="tel:+48503718007"><Phone size={16}/> 503 718 007</a></div></div><div className="hero-card"><img src={photos[0].src} alt="Weta Cafe"/><div><span>OTWARTE DZIŚ</span><strong>od 09:30</strong><small>Jana Mikulicza-Radeckiego 6</small></div></div></section>
 <section className="ticker"><span>ESPRESSO</span><b>·</b><span>FLAT WHITE</span><b>·</b><span>CEREMONIALNA MATCHA</span><b>·</b><span>COŚ SŁODKIEGO</span><b>·</b><span>WROCŁAW</span></section>
 <section id="o-nas" className="split"><div><p className="eyebrow">POZNAJMY SIĘ</p><h2>Mała przestrzeń,<br/><em>dużo charakteru.</em></h2></div><div className="body-copy"><p>Weta Cafe stawia na rzeczy, które po prostu dobrze smakują. Dobra kawa, matcha, zielone akcenty i przyjazne ceny tworzą miejsce na szybki poranek, spotkanie albo chwilę dla siebie.</p><p>Goście szczególnie doceniają ceremonialną matchę i kameralny klimat. To jeden z tych adresów, które łatwo zapamiętać.</p></div></section>
 <section id="menu" className="menu-section"><div className="section-head"><div><p className="eyebrow">CO DZIŚ?</p><h2>Proste rzeczy,<br/><em>dobrze zrobione.</em></h2></div><span className="price">1–20 zł / osoba</span></div><div className="menu-grid"><article><span>01</span><h3>Espresso</h3><p>Klasyczne, intensywne i krótkie.</p><strong>8 zł</strong></article><article><span>02</span><h3>Flat White</h3><p>Kawa i aksamitne mleko w dobrych proporcjach.</p><strong>12 zł</strong></article><article className="featured"><span>03</span><h3>Ice Matcha Latte</h3><p>Wyrazista ceremonialna matcha, mleko i lód.</p><strong>14 zł</strong></article><article><span>04</span><h3>Rurki z kremem</h3><p>Mała rzecz do kawy, która znika szybko.</p><strong>5 zł</strong></article></div></section>
 <section id="galeria" className="gallery"><div className="section-head"><div><p className="eyebrow">ZOBACZ NAS</p><h2>Trochę Wety<br/><em>w obrazkach.</em></h2></div><span>{photos.length} zdjęć</span></div><div className="gallery-grid">{photos.map((p,i)=><button className={"photo p"+(i%5)} key={p.src+i} onClick={()=>setOpen(i)}><img src={p.src} alt={p.alt}/><span>↗</span></button>)}</div></section>
 <section id="opinie" className="reviews"><div className="review-score"><p className="eyebrow">GOOGLE REVIEWS</p><div className="score">4,8 <span><Star fill="currentColor" size={18}/></span></div><p>31 opinii</p></div><div className="review-list"><blockquote>„Zdecydowanie jedna z lepszych match jakie piłam. Cena szokująco niska jak na Wrocław.”<cite>— Natalia K.</cite></blockquote><blockquote>„Fajne miejsce, espresso za 8 zł, rurki z kremem za 5 zł, dużo zieleni.”<cite>— Wrocławskie Podróże Kulinarne</cite></blockquote></div></section>
 <section id="kontakt" className="contact"><div><p className="eyebrow">WPADNIJ</p><h2>Do zobaczenia<br/><em>przy kawie.</em></h2><div className="contact-grid"><a href="tel:+48503718007"><Phone/>503 718 007</a><div><MapPin/>Jana Mikulicza-Radeckiego 6<br/>50-372 Wrocław</div><div><Clock3/>Godziny otwarcia<br/><span>Aktualne godziny sprawdź przed wizytą</span></div></div></div><div className="map"><iframe title="Mapa Weta Cafe" src="https://www.google.com/maps?q=Jana+Mikulicza-Radeckiego+6,+Wroc%C5%82aw&output=embed" loading="lazy"></iframe><a href="https://www.google.com/maps/dir/?api=1&destination=Jana+Mikulicza-Radeckiego+6,+Wroc%C5%82aw" target="_blank">Wyznacz trasę <ArrowUpRight size={16}/></a></div></section>
 <footer><div className="brand">WETA<span>CAFE</span></div><div>Wrocław · Mikulicza-Radeckiego 6</div><button onClick={()=>setPanel(true)}>Panel właściciela</button></footer>
 {open!==null&&<div className="lightbox" onClick={()=>setOpen(null)}><button className="close" onClick={()=>setOpen(null)}><X/></button><button className="arr left" onClick={e=>{e.stopPropagation();prev()}}><ChevronLeft/></button><img src={photos[open].src} alt={photos[open].alt} onClick={e=>e.stopPropagation()}/><button className="arr right" onClick={e=>{e.stopPropagation();next()}}><ChevronRight/></button><div className="counter">{open+1} / {photos.length}</div></div>}
 {panel&&<OwnerPanel photos={photos} setPhotos={setPhotos} onClose={()=>setPanel(false)}/>}
 </main>
}